spring.application.name=backend

spring.data.mongodb.uri=${MONGODB_URI}

server.port=${PORT:9999}

jwt.secret=${JWT_SECRET:QW5ub2FqYVNvY2lhbE1lZGlhSnNvbldlYlRva2VuU2VjcmV0S2V5MjAyNlZlcnlMb25nU2VjdXJlS2V5Rm9ySFMyNTY=}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB