spring.application.name=backend

spring.data.mongodb.uri=${MONGODB_URI}

server.port=${PORT:9999}

jwt.secret=${JWT_SECRET:QW5ub2FqYVNvY2lhbE1lZGlhSnNvbldlYlRva2VuU2VjcmV0S2V5MjAyNlZlcnlMb25nU2VjdXJlS2V5Rm9ySFMyNTY=}